spring.application.name=quietadmin-api

# Default profile can be overridden by env var SPRING_PROFILES_ACTIVE
spring.profiles.active=local

server.port=8180

# JPA common
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Flyway common
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT common (no secrets here)
security.jwt.expiration-seconds=900
security.jwt.refresh-expiration-seconds=2592000
security.jwt.clock-skew-seconds=60

security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=${JWT_ISSUER}
security.jwt.audience=${JWT_AUDIENCE}